#!/bin/zsh
# adds pyenv shims to path variable

# export PYENV_ROOT="$HOME/.pyenv" 
# export PATH="$PYENV_ROOT/bin:$PATH" 
# eval "$(pyenv init --path)" 
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
